version: 0.2

phases:
  pre_build:
    commands:
      - echo "Connexion a Docker Hub"
      - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - echo "Configuration de kubectl"
      - aws eks update-kubeconfig --region "$AWS_DEFAULT_REGION" --name "$EKS_CLUSTER_NAME"

  build:
    commands:
      - IMAGE_TAG=$(echo "$CODEBUILD_RESOLVED_SOURCE_VERSION" | cut -c 1-7)
      - echo "Construction de l'image Docker"
      - docker build -t "$DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$IMAGE_TAG" .
      - echo "Envoi de l'image vers Docker Hub"
      - docker push "$DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$IMAGE_TAG"

  post_build:
    commands:
      - IMAGE_TAG=$(echo "$CODEBUILD_RESOLVED_SOURCE_VERSION" | cut -c 1-7)
      - echo "Deploiement sur EKS"
      - kubectl set image deployment/aws-eks-cicd aws-eks-container="$DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$IMAGE_TAG"
      - kubectl rollout status deployment/aws-eks-cicd
      - echo "Deploiement termine"
